name: Continuous Integration for Deepspeech Version 2
on:
  # Run on manual trigger
  workflow_dispatch:

  # Run on pull requests
#  pull_request:
#    paths-ignore:
#      - '*.md'

  # Run when pushing to main or dev branches
#  push:
#    branches:
#      - main
#      - dev*

  # Run scheduled CI flow daily
#  schedule:
#    - cron: '0 8 * * 0'

jobs:
  test_deepspeech_v2:
    name: A job to test deepspeech version 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo for Local Action
        uses: actions/checkout@v2
      - name: Run Docker Container
        uses: ./.github/actions/deepspeech-v2
      - name: Checkout Repo for Tests
        uses: actions/checkout@v2
      - name: Run Tests
        uses: ./.github/actions/run.sh
#      - name: Run ${{ matrix.name }} Tests
#        run: ./run_tests.sh ${{ matrix.framework }}
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
