name: CI
on:
  # Run on manual trigger
  workflow_dispatch:

  # Run on pull requests
  pull_request:
    paths-ignore:
      - '*.md'

  # Run when pushing to main or dev branches
  push:
    branches:
      - main
      - dev*

  # Run scheduled CI flow daily
  schedule:
    - cron: '0 8 * * 0'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: PyTorch (Python 3.7)
            framework: pytorch
            python: 3.7
            torch: 1.6.0+cpu
            torchvision: 0.7.0+cpu
            torchaudio: 0.6.0

    name: ${{ matrix.name }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y -q install ffmpeg libavcodec-extra
          python -m pip install --upgrade pip setuptools wheel
          pip3 install -q -r requirements.txt
          pip list
      - name: Pre-install torch
        if: ${{ matrix.framework == 'pytorch' }}
        run: |
          pip install torch==${{ matrix.torch }} -f https://download.pytorch.org/whl/torch_stable.html
          pip install torchvision==${{ matrix.torchvision }} -f https://download.pytorch.org/whl/torch_stable.html
          pip install torchaudio==${{ matrix.torchaudio }} -f https://download.pytorch.org/whl/torch_stable.html
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Test Action
        uses: ./.github/actions/PyTorchFasterRCNN
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
